{
 "title": "Velib SQL",
 "tags": [
  "SQL",
  "GCP",
  "SLA"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "options": {
    "content": "# Google Cloud Instances Status\nThe GCP part consists of Google SQL (Postgres) and a scheduled runner to poll Velib' public API. Data is loaded in the beginning of each hour."
   }
  },
  {
   "title": "Last Hour Stations",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "velib_status_last_hour_stations",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Hour Rows",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "velib_status_last_hour_rows", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GCP SQL Status",
   "type": "status-history",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(up{job=\"VelibGeneric\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "max(pg_db_size_bytes)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Rows Loaded by Google Runner",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "max(velib_status_last_hour_rows)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}