{
 "title": "Velib MLFlow",
 "tags": [
  "mlflow",
  "usage"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "options": {
    "content": "# Usage Status\nAll model training and prediction are registered withing MLFlow."
   }
  },
  {
   "title": "Total MLP FLow Model Runs",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(mlflow_runs)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Currently Running",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(mlflow_last_run_running)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Avg \"Fit\" Time in Seconds",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(mlflow_last_run_time{starter='fit'}[1y])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last \"Fit\" Time in Seconds",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mlflow_last_run_time{starter='train'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg \"Predict\" Time in Seconds",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(mlflow_last_run_time{starter='predict'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last \"Predict\" Time in Seconds",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mlflow_last_run_time{starter='predict'}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}