{
 "title": "Velib Data",
 "tags": [ "data" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Data Monitoring\n\nHere're last data counts with Kholmogorov-Smirnov two-samples tests statistics showing the maximum weighted gap between two distributions (bigger numbers mean bigger difference of the last loaded 30 days to preceding 30 days for the selected values)."
   }
  },
  {
   "title": "Rows Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "velibdata_count{selection=\"full\", metrics=\"all\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delta Outliers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "velibdata_count{selection=\"full\", metrics=\"delta_outliers\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NA Values",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "velibdata_count{selection=\"full\", metrics=\"na\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg KS Test",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(velibdata_kstest)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "30 Day Row Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "velibdata_count{selection=\"30d\", metrics=\"all\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KS Test ['delta'] 30 Days Sample",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "velibdata_kstest{metrics=\"delta\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KS Test ['temp'] 30 Days Sample",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "velibdata_kstest{metrics=\"temp\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KS Test ['precip'] 30 Days Sample",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "velibdata_kstest{metrics=\"precip\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KS Test ['vent'] 30 Days Sample",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "velibdata_kstest{metrics=\"vent\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}