{
 "title": "Velib SQL",
 "tags": [
  "SQL",
  "GCP",
  "SLA"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# Google Cloud Instances Status\nThe GCP part consists of Google SQL (Postgres) and a scheduled runner to poll Velib' public API. Data is loaded in the beginning of each hour."
   }
  },
  {
   "title": "Database Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "max(pg_db_size_bytes)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GCP SQL Status",
   "type": "status-history",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(up{job=\"VelibSQL\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stations Data Loaded by Google Runner",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "max(velib_status_last_hour_stations)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rows Loaded by Google Runner",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "max(velib_status_last_hour_rows)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}